### ISSUE TITLE
Replace @CheckForNull with @NonNull

### ISSUE THREAD

**Issue by XiongKezhi** [XiongKezhi/checks-api-plugin#18]
According to codingstyle: https://github.com/uhafner/codingstyle/blob/13767f1ef6a77a844899905839b2c6418b33e027/codacy/checkstyle.xml#L145

**Comment by XiongKezhi** [comment]
@uhafner I don't understand why `@CheckForNull` is not allowed here in the coding style, to avoid Null pointers exist? Also, if we follow this, before (say `String`) when we return a `null`, now we are going to return an empty string?

**Comment by timja** [comment]
> @uhafner I don't understand why `@CheckForNull` is not allowed here in the coding style, to avoid Null pointers exist? Also, if we follow this, before (say `String`) when we return a `null`, now we are going to return an empty string?

Neither CheckForNull is used quite a lot in Jenkins =/

**Comment by uhafner** [comment]
There are multiple annotations to allow `null` as value. I'm using the general `edu.umd.cs.findbugs.annotations.Nullable`. In order to have only this single annotation in my plugin I added the architecture check. The problem with `@CheckForNull` is that it is not analyzed by error prone and NullAway.

**Comment by uhafner** [comment]
The best thing is to avoid `null` as valid return value if possible.

**Comment by timja** [comment]
> There are multiple annotations to allow `null` as value. I'm using the general `edu.umd.cs.findbugs.annotations.Nullable`. In order to have only this single annotation in my plugin I added the architecture check. The problem with `@CheckForNull` is that it is not analyzed by error prone and NullAway.

as far as I understand spotbugs doesn't use `Nullable` but does use `CheckForNull`,

cc @oleg-nenashev

> The best thing is to avoid `null` as valid return value if possible.

absolutely

**Comment by uhafner** [comment]
Spotbugs does not report a warning if one uses ´Nullable´. It is only reported in IntelliJ and ErrorProne. I think I can remove the check from Checkstyle and move it to my ArchitectureTests. Then it is not flagged here...

**Comment by XiongKezhi** [comment]
I saw both `edu.umd.cs.findbugs.annotations.Nullable` and `http://findbugs.sourceforge.net/api/edu/umd/cs/findbugs/annotations/CheckForNull.html`, the reason we are still using it is that `javax.*` annotations have licenses issues and we can't find better replacements?

And for the situation to return a `String`, is it better to return an empty string than a `null` pointer?

**Comment by uhafner** [comment]
I'm not sure if I understand your last comment. SpotBugs defines three annotations 
- `edu.umd.cs.findbugs.annotations.Nonnull` 
- `edu.umd.cs.findbugs.annotations.Nullable` 
- `edu.umd.cs.findbugs.annotations.ChecksForNull` 

The other old annotations with the same name but the `javax.*` package should not be used anymore. 

> And so for the situation to return a String, is it better to return an empty string than a null pointer? But it seems return a null pointer gives the users a hint that some problems during the calling....

Rather then returning `null` the method that wants to return `null` should throw an exception (and not the consumer of the method).

**Comment by XiongKezhi** [comment]
Sorry, some problems with typing on my last comment, just saw annotations like `edu.umd.cs.findbugs.annotations.Nullable` are marked as deprecated, see http://findbugs.sourceforge.net/api/edu/umd/cs/findbugs/annotations/Nullable.html

**Comment by uhafner** [comment]
They are not `@Deprecated` anymore. Spotbugs reverted that since the JSR305 is dead (see https://github.com/spotbugs/spotbugs/issues/130).

**Comment by timja** [comment]
You need 4.x of spotbugs, older versions of Jenkins pull in 3.x as a transitive dep, I think of you make it an explicit dependency it’ll work

**Comment by uhafner** [comment]
I created a PR for NullAway: https://github.com/uber/NullAway/pull/397 

So I think it is save to continue to use SpotBugs `@CheckForNull` annotation. I'll remove the import check from the CheckStyle rules.

**Comment by timja** [comment]
Thanks! Nice work

**Comment by XiongKezhi** [comment]
Great! Thanks.
